### ISSUE TITLE
The project not working with java 11 - handshake failed

### ISSUE THREAD

**Issue by fabriceci** [IdeaUJetBrains/SpringBootDockerDemoDebug#3]
I investigated why I had the error **Unable to open debugger port ...: java.io.IOException "handshake failed - connection prematurally closed"** following your guide: https://www.jetbrains.com/help/idea/run-and-debug-a-spring-boot-application-using-docker-compose.html (this should be indicated btw that only work on java 8)

I just remarked that's caused by the java version. To reproduce the problem, clone this project, just change the java version to 11 and the image to FROM openjdk:11 and you will experience the issue. 

As java 11 is an LTS, can you fix this?
Is there a workaround to be able to debug a J11 project?

Thanks.

**Comment by IdeaUJetBrains** [comment]
It is the issue for JVM 9 or later: https://youtrack.jetbrains.com/issue/IDEA-247973.
Workaround is to edit Remote run configuration->Launch Docker Before Debug
write **address=*:5005** instead of **address=5005** in the "Custom Command" field
I've also created an issue to update our help - add all workarounds, see https://youtrack.jetbrains.com/issue/DOC-11420

**Comment by fabriceci** [comment]
@IdeaUJetBrains unfortunately it's not the issue, in the latest version IntelliJ use the right address:

![image](https://user-images.githubusercontent.com/6397893/108182406-428b4580-7109-11eb-8f27-230e8a471bcb.png)
(I tried with the port 5005 and 8765 as suggested in the issue I created: https://youtrack.jetbrains.com/issue/IDEA-262047, there is a minimal project inside the post in case you want to try quickly, and a second one with the exact same config in j8 that works flawlessly)

Hope there is a workaround, seems pretty basic to use j11  now.

**Comment by IdeaUJetBrains** [comment]
Note, that it is not that place to change the **address**. Thank you for the example project, the place that need to be changed is here(there is 8765 instead of *:8765)
![image](https://user-images.githubusercontent.com/14996705/108276200-bbc18180-7177-11eb-9c4f-a2e1f3e4465c.png)

**Comment by fabriceci** [comment]
Thanks, it works! I I thought it was using the command line arguments define in the Remote JVM Debug screen.
